### ISSUE TITLE
Bug: kusion generate cmd generate incorrect format for customized namespace

### ISSUE THREAD

**Issue by Yangyang96** [KusionStack/kusion#1208]
### What happened?

When adding 
`extensions:`
  `- namespace: xxxx`
  `- kind: kubernetesNamespace` to project.yaml, `kusion generate` command will generate a yaml file with `- id: 'v1:Namespace:'` on the 2nd line.

### What did you expect to happen?

The accurate format for the customized namespace of this yaml file generated by `kusion generate` command should be `- id: v1:Namespace: X`, with no single quote, and has the namespace at the end.

### How can we reproduce it (as minimally and precisely as possible)?

Add `extensions: - namespace: xxxx - kind: kubernetesNamespace` to project.yaml, and try `kusion generate` command afterwards. Check out the 2nd line of the generated file to review this bug.

### Kusion version

<details>

```console
$ kusion version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

**Comment by SparkYuan** [comment]
Thanks for your feedback! We will attempt to reproduce the issue, and if it indeed exists, we will fix it in the next version.

**Comment by liu-hm19** [comment]
It seems that the problem is due to the unclear documentations of customized namespace in `project.yaml` and `stack.yaml`. In fact, the configuration items for customized namespace should be as follows: 

```yaml
# Example `project.yaml` file with customized namespace of `test`. 
name: example
extensions: 
    - kind: kubernetesNamespace
      kubernetesNamespace: 
        namespace: test
```

The customized `Namespace` resource will be generated correctly if we configure as the example above. And I have updated the relevant documentations in this [PR](https://github.com/KusionStack/kusionstack.io/pull/545).
