### ISSUE TITLE
Feat: Add support for removing specific env with patcher in kusion module generatorResponse

### ISSUE THREAD

**Issue by Liuxingyu1111111** [KusionStack/kusion#1271]
### What would you like to be added?

Now kusion patcher can only add env for workload in kusion module generatorResponse, if I want remove a env with specific env name. I found it can't be support by environment define in kusion module generatorResponse or JsonPatch

### Why is this needed?

In my case, a feature in kusion module is to remove a specific env in workload.

**Comment by liu-hm19** [comment]
Due to the lack of support for value-based array operations in the existing JSON Patch specification, and the related discussions seem to have stagnant for many years, we will implement value-based array removal operation by agreeing on a specific value (`ops://kusionstack.io/remove`) as the `remove` operation index for the environment variable patcher to solve this issue. 

For example, if we want to remove an environment variable whose name is `REMOVAL_ENV`, developers for the related module can set the patcher as follows: 

```go
...
envVars := []v1.EnvVar{
    {
        Name: "REMOVAL_ENV",
        Value: "ops://kusionstack.io/remove"
    }
}

patcher := &apiv1.Patcher{
    Environments: envVars,
}
...
```

cc @Liuxingyu1111111 @ffforest 

Ref: 
- https://github.com/json-patch/json-patch2/issues/18
- https://github.com/json-everything/json-everything/issues/209
- https://github.com/json-everything/json-everything/issues/287
