### ISSUE TITLE
KCL Compile Error[E2F04] : Cannot find the module

### ISSUE THREAD

**Issue by akan** [KusionStack/kusion#142]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

按教程，kusionup
 kusion init --online
进入code-city/dev
执行：kusion apply

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
✘  Compiling in stack dev...                                                                               
 ❌  KCL Compile Error[E2F04] : Cannot find the module
      Cannot find the kcl file, please check whether the file path /base/pkg/kusion_models/kube/metadata/metadata.k

### 4. What is your KusionStack components version? (Required)

releaseVersion: v0.6.1-rc.0
gitInfo:
    latestTag: v0.6.1-rc.0
    commit: e496ce1920ddba036f95299bb360363b99c29d89
    treeState: clean
buildInfo:
    goVersion: go1.17.13
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2022-09-07 06:30:06"
dependency:
    kclvmgoVersion: v0.4.3-alpha.4
    kclPluginVersion: v0.4.1-alpha2

**Comment by howieyuen** [comment]
Maybe is the guideline not quite clear. Let me reword the whole process:
1. install kusionup and run `kusionup install`,  choose the version you prefer (latest is recommended)
2. git clone [konfig repo](https://github.com/KusionStack/konfig), because user project depends on base models from konfig repo
3. enter the root path of konfig repo, and run `kusion init --online`, choose the `code-city` template
4. run `kusion apply` at path `code-city/dev`

Please run `kusion init --online` in konfig repo.

Sorry, I am late, happy coding.
