### ISSUE TITLE
Feature: update Kusion init template with the new AppConfig model

### ISSUE THREAD

**Issue by SparkYuan** [KusionStack/kusion#468]
### What would you like to be added?

1. update the init template of the WordPress and go-city example with the new AppConfig model
2. update related documentation on the website

### Why is this needed?

We upgraded our models and quick-start examples should also be updated.

**Comment by SparkYuan** [comment]
#385

**Comment by healthjyk** [comment]
As far as I'm concerned, there are three things left to do:
1, make repo catalog a kcl package, and register it so it can be used by others. There are two registry options: ghcr.io and OCI registry. Kusion may have OCI registry, which needs to check;
2, add init template in kusion init;
3, use "kpm run" instead of "kcl -Y" to render kcl json/yaml, when generating spec.
Could you accomplish it? @panshuai-ps @elliotxx
